CREATE TABLE data_lineage (lineage_id NUMBER PRIMARY KEY, source_object VARCHAR2(100), source_column VARCHAR2(100), target_object VARCHAR2(100), target_column VARCHAR2(100), transformation_rule VARCHAR2(1000), lineage_type VARCHAR2(30), created_date DATE DEFAULT SYSDATE);
INSERT INTO data_lineage VALUES(1,'ACCOUNT','CURRENT_BALANCE','LIQUIDITY_REPORT','INFLOW_AMOUNT','SUM(CURRENT_BALANCE) WHERE ACCOUNT_STATUS = ''ACTIVE''','DIRECT',SYSDATE);
INSERT INTO data_lineage VALUES(2,'BANK_TRANSACTION','AMOUNT','LIQUIDITY_REPORT','OUTFLOW_AMOUNT','SUM(AMOUNT) WHERE TRANSACTION_TYPE = ''OUTFLOW''','AGGREGATION',SYSDATE);
INSERT INTO data_lineage VALUES(3,'LIQUIDITY_REPORT','INFLOW_AMOUNT','LIQUIDITY_REPORT','LIQUIDITY_GAP','INFLOW_AMOUNT - OUTFLOW_AMOUNT','CALCULATION',SYSDATE);
INSERT INTO data_lineage VALUES(4,'LIQUIDITY_REPORT','OUTFLOW_AMOUNT','LIQUIDITY_REPORT','LIQUIDITY_GAP','INFLOW_AMOUNT - OUTFLOW_AMOUNT','CALCULATION',SYSDATE); COMMIT;
